name: Update & Deploy to production

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-and-make:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      run: |
        sshpass -p 'sosu228' ssh -o StrictHostKeyChecking=no greg@unicort.ru << EOF
        cd tg-updates-handler
        git pull
        cd ../Backend
        git pull
        make prod
